http-port=8080
enable-html-templates-caching=false
mqtt-port=1883
mqtt-salt=SecretSalt123
mdns-service-name=DoorbellRelayServer
mdns-service-description=IDS system broker
db-path=data.db
db-pool-size=5
session-ttl-sec=7200
session-clear-interval-sec=3600
admin-username=admin
admin-password-length=20
admin-password-hash-strength=10
