name: Build and create docker image of relay server

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/relay-server.yml"
      - "relay_server/**"
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version in format X.X.X"
        required: false
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./relay_server

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"
          cache: "gradle"

      - name: Determinate build version
        id: version
        run: |
          echo "sha_full=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo "${{ github.sha }}" | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: |
          ./gradlew clean --no-daemon
          ./gradlew test --no-daemon -PcommitHash=${{ steps.version.outputs.sha_full }}
        env:
          RELAY_SERVER_VERSION: ${{ steps.version.outputs.sha_short }}

      - name: Package to JAR
        run: |
          ./gradlew clean --no-daemon
          ./gradlew shadowJar --no-daemon -PcommitHash=${{ steps.version.outputs.sha_full }}
        env:
          RELAY_SERVER_VERSION: ${{ steps.version.outputs.sha_short }}

      - name: Copy JAR file into docker directory
        run: |
          mv .bin/relay_server.jar docker/relay_server.jar
          rm -rf .bin

      - name: Set up builder
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./relay_server
          file: ./relay_server/Dockerfile.pipeline
          push: true
          tags: ghcr.io/milosz08/intelligent-doorbell-relay-server:${{ inputs.version || 'latest' }}
          platforms: linux/amd64,linux/arm64
